//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilgiEkle
    {
        public int Menu_id { get; set; }
        public string Menu_ad { get; set; }
        public Nullable<int> Menu_sira { get; set; }
        public string Menu_yetki { get; set; }
        public string Menu_adres { get; set; }
    }
}
