//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Personel_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Personel_Table()
        {
            this.Cocuk_Table = new HashSet<Cocuk_Table>();
        }
    
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyadi { get; set; }
        public string Telefon { get; set; }
        public string TC { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> Hastane { get; set; }
        public Nullable<int> Cinsiyet { get; set; }
    
        public virtual Cinsiyet_Table Cinsiyet_Table { get; set; }
        public virtual Hastane_Table Hastane_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cocuk_Table> Cocuk_Table { get; set; }
    }
}
