//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class islem_Table
    {
        public int id { get; set; }
        public Nullable<int> Turu { get; set; }
        public Nullable<int> Yapan_Kisi { get; set; }
        public Nullable<int> Alan_kisi { get; set; }
    
        public virtual Aile_bilgiler_Table Aile_bilgiler_Table { get; set; }
        public virtual Devlet_memur_Table Devlet_memur_Table { get; set; }
        public virtual islem_turu_Table islem_turu_Table { get; set; }
    }
}
