//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici_Table
    {
        public int Kullanici_id { get; set; }
        public string Kullanici_ad { get; set; }
        public string Kullanici_email { get; set; }
        public string Kullanici_TC { get; set; }
        public string Kullanici_sifresi { get; set; }
        public string Kullanici_Yetki { get; set; }
    }
}
