//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_DataEntities : DbContext
    {
        public Project_DataEntities()
            : base("name=Project_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Personel_Table> C_Personel_Table { get; set; }
        public virtual DbSet<Aile_bilgiler_Table> Aile_bilgiler_Table { get; set; }
        public virtual DbSet<BilgiEkle> BilgiEkle { get; set; }
        public virtual DbSet<Cinsiyet_Table> Cinsiyet_Table { get; set; }
        public virtual DbSet<Cocuk_Table> Cocuk_Table { get; set; }
        public virtual DbSet<Devlet_memur_Table> Devlet_memur_Table { get; set; }
        public virtual DbSet<Hastane_Table> Hastane_Table { get; set; }
        public virtual DbSet<islem_Table> islem_Table { get; set; }
        public virtual DbSet<islem_turu_Table> islem_turu_Table { get; set; }
        public virtual DbSet<Kullanici_Table> Kullanici_Table { get; set; }
        public virtual DbSet<Sehir_Table> Sehir_Table { get; set; }
        public virtual DbSet<Sube_Table> Sube_Table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
